[package]
name = "voxel_coarsen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_reader = {git="https://github.com/rcarson3/rust_data_reader.git"}
anyhow = {version="1.0"}
rand = {version = "0.8"}
polars = {version = "0.30.0", optional=true, features = ["csv"]}
numpy = {version = "0.21", optional=true}
pyo3 = { version = "0.21", optional=true, features = ["abi3-py37", "extension-module", "multiple-pymethods", "anyhow"] }

[features]
python = ["numpy", "pyo3"]
polar = ["polars"]

[lib]
name = "voxel_coarsen"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.test]
opt-level = 3
debug = false
lto = true
incremental = false
codegen-units = 1